name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Runs when you push to main branch
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  

      - name: Setup Pages
        uses: actions/configure-pages@v4  

      - name: Create config.js
        run: echo "const RECAPTCHA_SITE_KEY = '${{ secrets.RECAPTCHA_SITE_KEY }}';" > config.js 

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4