name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Runs when you push to main branch
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'  # Specify the Node.js version

      - name: Install Dependencies
        run: npm install  # Adjust this if you're using yarn or another package manager

      - name: Build Project
        run: npm run build  # Ensure this script generates your static files into a 'dist' directory

      - name: Create config.js
        run: echo "const RECAPTCHA_SITE_KEY = '${{ secrets.RECAPTCHA_SITE_KEY }}';" > dist/config.js

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist  # Ensure this matches the output directory of your build
          name: github-pages  # Name the artifact 'github-pages'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2