name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Runs when you push to main branch
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # ✅ Latest version

      - name: Setup Pages
        uses: actions/configure-pages@v4  # ✅ Latest version

      - name: Create config.js
        run: echo "const RECAPTCHA_SITE_KEY = '${{ secrets.RECAPTCHA_SITE_KEY }}';" > config.js  # ✅ Generate `config.js`

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v2  # ✅ `v2` is the correct latest version
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2  # ✅ `v2` is the correct latest version

      - name: Create a file
        run: echo "hello world" > my-file.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact # NOTE: same artifact name
          path: my-file.txt

    upload-again:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: Create a different file
        run: echo "goodbye world" > my-file.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact # NOTE: same artifact name
          path: my-file.txt